### ISSUE TITLE
Extension not showing up in gaffer

### ISSUE THREAD

**Issue by nyue** [andrewkaufman/gafferExtensionDemo#1]
I have compiled the extension against Gaffer 0.50.0.0 (linux) and followed the README instruction about setting the GAFFER_EXTENSIONS_PATH to the installed location (where I can see the directories lib, python and startup)

When I started gaffer, I hit tab but I don't see the demo extension showing up.

Is there a debug/verbose mode in Gaffer that prints out diagnostic messages that may help in debugging the issue ?

**Comment by andrewkaufman** [comment]
Hi, sorry about that, I haven't run this demo in a while. I've added the missing imports to the python init files. Can you try it again after updating from master?

**Comment by andrewkaufman** [comment]
Note, I haven't actually tested my changes... I just threw them in there via the GitHub Web interface...

**Comment by nyue** [comment]
I pulled your changes, rebuild and reinstalled. It does not show up in the Gaffer UI

I tried debugging the problem via the command line python interface with the following sequence of steps but still not successful.

[nicholas@e6410 build]$ env | grep ^GAFFER
GAFFER_ROOT=/home/nicholas/systems/gaffer/gaffer-0.50.0.0-linux
GAFFER_EXTENSION_PATHS=/home/nicholas/temp/gafferExtensionDemo
[nicholas@e6410 build]$ ls /home/nicholas/temp/gafferExtensionDemo
lib  python  startup
[nicholas@e6410 build]$ gaffer env python -c "DemoGafferExtension"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'DemoGafferExtension' is not defined

Cheers

**Comment by andrewkaufman** [comment]
Hi, sorry it took me so long but I finally found time to recompile this. I think maybe its just a misunderstanding on my part, but if I do the following it seems to work as expected:

`gaffer env python -c 'import DemoGafferExtension; print dir(DemoGafferExtension)'`

**Comment by nyue** [comment]
Thanks for the update. I will try that out soon.
