### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by kubo-von** [andrewkaufman/gafferExtensionDemo#10]
Hello,
Not really an issue, just wanted to mention a fork I've made with small fixes needed to build the demo with 
**gaffer-0.59.4.0-linux-python3**

[https://github.com/kubo-von/gafferExtensionDemo/commits/master](https://github.com/kubo-von/gafferExtensionDemo/commits/master)

@andrewkaufman  I can open a PR if you like, but maybe it doesn't make sense atm.
Just though this might save someone wanting to build against python3 gaffer a little bit of work. 
Cheers

**Comment by andrewkaufman** [comment]
Feel free to make a PR with the python changes, those should be 2/3 compatible anyways. For the cmake/build changes though, we'd need to refactor a bit so both builds are still possible. Adding a new PYTHON_VERSION arg seems ok to me.

**Comment by kubo-von** [comment]
Addressed in #11
